"""Brief description of changes

Revision ID: 306684d51019
Revises: 
Create Date: 2024-06-27 23:13:03.227117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '306684d51019'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'todos', 'users', ['owner_id'], ['id'])
    op.drop_column('todos', 'completed')
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.add_column('todos', sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'todos', type_='foreignkey')
    op.drop_column('todos', 'owner_id')
    # ### end Alembic commands ###
